version = 1

[merge]
delete_branch_on_merge = true
method = "squash"
prioritize_ready_to_merge = true
priority_merge_label = "automerge_priority"

[merge.automerge_dependencies]
usernames = ["dependabot"]
versions = ["minor", "patch"]

[approve]
auto_approve_usernames = ["dependabot", "github-actions", "MichaelHatherly"]
